### ISSUE TITLE
Can't install hic-straw with pip in conda

### ISSUE THREAD

**Issue by mozesjacobs** [aidenlab/straw#112]
**Describe the bug**
When I try to install the package using a conda environment, it doesn't seem to work. I get an error related to curl/curl.h. It has something to do with the c package, I think.

**To Reproduce**

Using environment.yml file
1. Use this file as a conda environment: https://github.com/Noble-Lab/pastis-protocol/blob/main/environment.yml2. 
2. Run "conda env create -f environment.yml"

**Expected behavior**
The installation fails with this error:

src/straw.cpp:34:10: fatal error: curl/curl.h: No such file or directory
         34 | #include <curl/curl.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/net/noble/vol1/home/mozesj/anaconda3/envs/protocol/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
      [end of output]
  

**Desktop (please complete the following information):**
 - OS: CentOS Linux
 - Version: 7 (Core)
 - x86-64 machine

**Additional context**
When I remove the line that installs hic-straw line from the environment.yml file, the installation of the environment works, so something is happening when I make the environment include the environment.yml file.

**Comment by sa501428** [comment]
Curious, does it work if you also include curl? https://anaconda.org/conda-forge/curl

**Comment by mozesjacobs** [comment]
That fixed it!

**Comment by mozesjacobs** [comment]
Thank you!

**Comment by fage66639** [comment]
I have the same question. Has it been resolved?
