### ISSUE TITLE
Configure query

### ISSUE THREAD

**Issue by Sen0108** [aidenlab/straw#118]
What sort of configuration is needed for all the Juicebox packages? Likes GPUs, RAM, etc.?

**Comment by sa501428** [comment]
I've approved your question on the forum.

**Comment by sa501428** [comment]
https://groups.google.com/g/3d-genomics/c/TbDKSFiMLm8

**Comment by Sen0108** [comment]
thanks

From: Muhammad Saad Shamim ***@***.***>
Date: Friday, October 21, 2022 at 1:36 PM
To: aidenlab/straw ***@***.***>
Cc: Sen, Sagnik ***@***.***>, Author ***@***.***>
Subject: Re: [aidenlab/straw] Configure query (Issue #118)
EXTERNAL SENDER


I've approved your question on the forum.
