### ISSUE TITLE
Segmentation fault when calling mzd.getRecordsAsMatrix

### ISSUE THREAD

**Issue by WangJiuming** [aidenlab/straw#125]
I am trying to load the contact map of an entire chromosome as an array. A segmentation fault occurred when calling the getRecordsAsMatrix() method. I originally applied it on some local data downloaded from 4DN and GEO, and later tested with an URL in the Juicebox menu (see code below). The error persisted in all cases.

Here is the code to reproduce the error.
```
import hicstraw

if __name__ == '__main__':
    chr_num = '1'

    hic_obj = hicstraw.HiCFile('https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/combined.hic')

    mzd = hic_obj.getMatrixZoomData(chr_num, chr_num, 'observed', 'NONE', 'BP', 10000)

    chr_dict = {c.name: c for c in hic_obj.getChromosomes()}  # chr number as a str: chr object

    matrix = mzd.getRecordsAsMatrix(0, chr_dict[chr_num].length, 0, chr_dict[chr_num].length)
```

The exact error in this case is simply
```
Segmentation fault (core dumped)
```

For your reference, I am working with hic-straw version 1.3.1 and  the ```getRecords()``` method seems to work fine.

May I ask if this indicates an error in the package or there is any alternative recommended way of efficiently loading the contact map of an entire chromosome? 

Thanks in advance!

**Comment by sa501428** [comment]
Does it work with chr1 instead of 1?
- Muhammad Saad Shamim <http://mshamim.com/>

**Comment by WangJiuming** [comment]
Hi, thanks for your prompt help! 

Unfortunately, using 'chr1' instead of '1' would give rise to a KeyError instead.
```
Error finding block data
Traceback (most recent call last):
  File "/home/code/test.py", line 12, in <module>
    matrix = mzd.getRecordsAsMatrix(0, chr_dict[chr_num].length, 0, chr_dict[chr_num].length)
KeyError: 'chr1'

Process finished with exit code 1
```

**Comment by sa501428** [comment]
Oh wait, I misread the original message.
Yeah it looks like you're trying to create a dense 25000x25000 matrix -
that will not work well.
You can use the records list to create a scipy sparse matrix if you need
the entire matrix all at once.

- Muhammad Saad Shamim <http://mshamim.com/>

**Comment by WangJiuming** [comment]
I see. Thanks for your help! I will close this issue now.
