### ISSUE TITLE
Small test data

### ISSUE THREAD

**Issue by joachimwolff** [aidenlab/straw#44]
Hi,

I would like to implement support for the `hic` format for Galaxy (https://github.com/galaxyproject/galaxy). For this I need test data for a functional test if the file format detection is working as it should. Do you have any `hic` file with a file size < 1MB that I could use for this purpose? I looked in your repository here, but it seems you don't have test cases? And in the ipython notebook, the URL: https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/HIC001.hic is given, but I only get  a `ERROR 403: Forbidden` error using wget. 

Best,

Joachim

**Comment by sa501428** [comment]
Hey @joachimwolff 
Would be great to see support for this on Galaxy! Our test sets tend to be larger but I've uploaded a smaller .hic file that's 5MB here: [https://bcm.box.com/v/juicer-tools-testing](https://bcm.box.com/v/juicer-tools-testing)

Note that this test file only has two resolutions, 2.5MB and 100KB.
