### ISSUE TITLE
is the strawc package on bioconda official?

### ISSUE THREAD

**Issue by TTTPOB** [aidenlab/straw#75]
it seems the package on [bioconda](https://anaconda.org/bioconda/strawc) update quite slowly comparing to github

**Comment by sa501428** [comment]
@nchernia and I did not upload it. 
@cwenger @zozo123 is this something you uploaded?

**Comment by cwenger** [comment]
@sa501428 No, have not uploaded anything related to straw at this point.

**Comment by sa501428** [comment]
@TTTPOB unless this was uploaded by @zozo123, it's possible this was an unofficial upload to bioconda. The best way to download the latest would be from github.

**Comment by zozo123** [comment]
@sa501428 
It's not official, AFAIK. I am modestly suggesting users to install directly from the repository or use the pip release.

**Comment by sa501428** [comment]
Seems like an unofficial upload then @TTTPOB. The pip release is official as @zozo123 mentioned, although we do need to update it. The latest dev version can be installed from Github.
