### ISSUE TITLE
Declare curl in SystemRequirements in the R package

### ISSUE THREAD

**Issue by Enchufa2** [aidenlab/straw#80]
Since `curl.h` is required, it should be declared in SystemRequirements.

**Comment by sa501428** [comment]
@cwenger would you be able to handle this?

**Comment by cwenger** [comment]
@Enchufa2 Can you elaborate on this, or do a pull request? I don't have a full understanding of how the build works, especially on Windows where I used the configuration from https://github.com/jeroen/curl. They have:
`SystemRequirements: libcurl: libcurl-devel (rpm) or libcurl4-openssl-dev (deb).` so I can add that if it's helpful.

**Comment by Enchufa2** [comment]
Per the [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) manual,

> Dependencies external to the R system should be listed in the ‘SystemRequirements’ field

Adding Jeroen's line would do.

**Comment by cwenger** [comment]
Done. Thanks for the suggestion.
